require 'huginn_agent'

#HuginnAgent.load 'huginn_http_observatory_mozilla_agent/concerns/my_agent_concern'
HuginnAgent.register 'huginn_http_observatory_mozilla_agent/http_observatory_mozilla_agent'
